"""initial schema

Revision ID: 292ed36c3e49
Revises: 
Create Date: 2026-08-07 00:56:13.983512

"""
from alembic import op
import sqlalchemy as sa


revision = '292ed36c3e49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('final_capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_uuid', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('ml_features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_entry_uuid'), 'knowledge_entries', ['entry_uuid'], unique=True)
    op.create_index(op.f('ix_knowledge_entries_instrument'), 'knowledge_entries', ['instrument'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_pattern'), 'knowledge_entries', ['pattern'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_timeframe'), 'knowledge_entries', ['timeframe'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('pattern_name', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('actual_outcome', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_uuid', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_name', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_uuid'), 'signals', ['signal_uuid'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_uuid', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pattern_name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_trade_uuid'), 'trades', ['trade_uuid'], unique=True)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_uuid', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_name', sa.String(length=50), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('key_levels', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_pattern_uuid'), 'patterns', ['pattern_uuid'], unique=True)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifecycles')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_patterns_pattern_uuid'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_table('candles')
    op.drop_index(op.f('ix_trades_trade_uuid'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_signal_uuid'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('predictions')
    op.drop_table('ml_models')
    op.drop_table('metrics')
    op.drop_table('logs')
    op.drop_index(op.f('ix_knowledge_entries_timeframe'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_pattern'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_instrument'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_entry_uuid'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
